version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '54320:5432'
    environment:
      POSTGRES_USER: cusco_user
      POSTGRES_DB: cusco_trips # THIS MUST MATCH YOUR DB NAME IN .env
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
